#Run the DESeq2 pipeline on the raw counts
#' Run the DESeq2 pipeline on subsetted & ordered data & metadata.
#'
#' This function takes the ordered count data, metadata, along with information regarding-
#' -the reference factor (e.g. treatment), reference level (e.g. PBS vehicle), & contrast vector-
#' -(e.g. c("Treatment", "Drug 1", "PBS vehicle)) to run the DESeq2 pipeline.
#' The results names & summary is printed, & a list containing the dds object & results table is returned.
#'
#' @param count_data Data frame. Containing integer values of raw gene counts generated by HTSeq or featureCounts.
#' @param metadata Data frame. The matched & ordered metadata .csv file.
#' @param design_formula A formula object defining the experimental design (e.g. ~ Age + Treatment)
#' @param reference_factor Character. The name of the variable by which data will be re-leveled & compared based on (e.g. Treatment). NEEDS TO BE PRESENT IN METADATA FILE.
#' @param reference_level Character. The name of the control condition which serves as the denominator for calculating the DEGs (e.g. PBS vehicle). NEEDS TO BE PRESENT IN METADATA FILE.
#' @param contrast_vector Character vector. Definition of the reference factor, the treatment condition & reference level for contrasting & extracting results (e.g. c("Treatment", "Drug 1", "PBS vehicle"))
#'
#' @returns A list containing the DESeqDataSet (dds) object & the results table.
#' @export
#'
run_deseq2 <- function(count_data, metadata, design_formula, reference_factor, reference_level, contrast_vector) {

  #Ensure all values in the counts data are integers & data is within a matrix for the DESeq2 pipeline
  count_matrix <- round(as.matrix(count_data))

  message("Creating DESeq2 object...")

  dds <- DESeq2::DESeqDataSetFromMatrix(countData = count_matrix,
                                        colData = metadata,
                                        design = design_formula)

  message("Releveling", reference_factor, "according to reference level- ", reference_level, "...")

  dds[[reference_factor]] <- stats::relevel(as.factor(dds[[reference_factor]]), ref = reference_level)

  message("Now running DESeq2 pipeline...")
  dds <- DESeq2::DESeq(dds)

  message("Contrasting & extracting results...")
  res <- DESeq2::results(dds, contrast = contrast_vector)

  message("Yay! Successfully completed DESeq2 pipeline!")

  message("\n--- Available Contrasts, use [3] for LFC shrink ---")
  print(DESeq2::resultsNames(dds))

  message("\n--- Results Summary ---")
  print(summary(res))

  return(list(
    dds_object = dds,
    results_table = res
  ))

}

#Print DESeq2 results as csv
#' Exports DESeq2 DEG results in the working directory.
#'
#' This function orders the DEGs within the dds object & orders it based on the p-value &-
#' exports the file as provided by the user within the current working directory.
#'
#' @param deseq2_res A DESeqResults object.
#' @param file_name Character. The name of the desired file output (e.g. "results.csv")
#'
#' @export
#'
print_results <- function(deseq2_res, file_name) {

  #Order resulst from DESeq2 according to p-value
  res_ordered <- deseq2_res[order(deseq2_res$pvalue), ]

  message("\n--- Top 6 Ordered DESeq2 Results ---")
  print(utils::head(res_ordered))

  res_export <- as.data.frame(res_ordered)

  res_export <- cbind(GeneID = rownames(res_export), res_export)

  utils::write.csv(res_export, file = file_name, row.names = FALSE)

  message("Yay! Successfully written", file_name, ", ordered by p-value!")
}
